Update Deploy-TaskProject-To-Azure.yml

diff --git a/.github/workflows/Deploy-TaskProject-To-Azure.yml b/.github/workflows/Deploy-TaskProject-To-Azure.yml
--- a/.github/workflows/Deploy-TaskProject-To-Azure.yml
+++ b/.github/workflows/Deploy-TaskProject-To-Azure.yml
@@ -70,12 +70,12 @@ jobs:
 
       - name: 🔍 Verificar existencia del archivo ZIP
         run: |
-          if [ -f "deploy.zip" ]; then
-          echo "✅ deploy.zip encontrado."
-          else
-          echo "❌ ERROR: deploy.zip no se generó correctamente."
-          exit 1
-          fi
+            if [ -f "deploy.zip" ]; then
+            echo "✅ deploy.zip encontrado."
+            else
+            echo "❌ ERROR: deploy.zip no se generó correctamente."
+            exit 1
+            fi
           
       - name: ⬆️ Upload the zip in artifact
         uses: actions/upload-artifact@v4
