Update Deploy-TaskProject-To-Azure.yml

diff --git a/.github/workflows/Deploy-TaskProject-To-Azure.yml b/.github/workflows/Deploy-TaskProject-To-Azure.yml
--- a/.github/workflows/Deploy-TaskProject-To-Azure.yml
+++ b/.github/workflows/Deploy-TaskProject-To-Azure.yml
@@ -59,8 +59,6 @@ jobs:
       - name: 🛫 Generate Publish
         run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -c ${{ env.BUILD_CONFIG }} -o "${{ env.PACKAGE_NAME }}" --no-build --no-restore
 
-      - name: 📂 Verificar archivos en el directorio de publicación
-        run: ls -la "${{ env.PACKAGE_NAME }}"
         
       - name: 🗜️ Generar archivo .zip
         run: |
@@ -70,18 +68,18 @@ jobs:
 
       - name: 🔍 Verificar existencia del archivo ZIP
         run: |
-            if [ -f "deploy.zip" ]; then
-            echo "✅ deploy.zip encontrado."
-            else
-            echo "❌ ERROR: deploy.zip no se generó correctamente."
-            exit 1
-            fi
+         if [ -f "deploy.zip" ]; then
+         echo "✅ deploy.zip encontrado."
+         else
+         echo "❌ ERROR: deploy.zip no se generó correctamente."
+         exit 1
+         fi
           
       - name: ⬆️ Upload the zip in artifact
         uses: actions/upload-artifact@v4
         with:
           name: dotnet-app
-          path: ./deploy.zip
+          path: deploy.zip
 
       - name: Listar artefactos disponibles
         run: ls -R ${{ github.workspace }}
